[project]
name = "dbt-homeserver"
version = "2.0.0"
description = "dbt project to manage data transformations on the kubernetes clickhouse"
requires-python = ">=3.11"
dependencies = [
    "dbt-core==1.11.12",
    "dbt-clickhouse==1.10.1",
    "sqlfluff==3.1.0",
    "sqlfluff-templater-dbt==3.1.0"
]
