version: 2

models:

  - name: sat_crypto_order_binance
    description: Satellite for orders from binance.
  
  - name: sat_crypto_order_bybit
    description: Satellite for orders from bybit.

  - name: sat_crypto_trade_bybit
    description: Satellite for trades from the bybit platform.

  - name: link_crypto_pnl_crypto_order
    description: Link from crypto PnL to crypto order on bybit.
  
  - name: link_crypto_trade_crypto_order
    description: Link from crypto trade to crypto order on bybit.
